default['gemfire']['config_cache']['group'] = 'gemuser'
default['gemfire']['config_cache']['user'] = 'gemuser'
default['gemfire']['config_cache']['home'] = '/home'

default['gemfire']['config_cache']['action'] = 'addServer'
default['gemfire']['config_cache']['locator_port'] = '41111'
default['gemfire']['config_cache']['server_port'] = '40404'
default['gemfire']['config_cache']['locator_list'] = 'localhost[41111]'
default['gemfire']['config_cache']['server_max_heap'] = '4096M'
default['gemfire']['config_cache']['adv_jvm_args'] = 'abcd'
default['gemfire']['config_cache']['gemfire_prop_file'] = 'default'
default['gemfire']['config_cache']['server_max_connections'] = '1500'

default['gemfire']['config_cache']['java_home'] = '/usr/lib/jvm/java'
default['gemfire']['config_cache']['gemfire_home'] = '/apps/gemfire/8.2.0/b17919'
default['gemfire']['config_cache']['gemfire_install_dir'] = '/apps/gemfire'
default['gemfire']['config_cache']['gemfire_config_dir'] = '/apps/gemfire/config'
default['gemfire']['config_cache']['logs_home_dir'] = '/logs/gemfire'

default['gemfire']['config_cache']['is_profile'] = 'true'
default['gemfire']['config_cache']['profile_name'] = 'profile1'
default['gemfire']['config_cache']['profile_home_dir'] = '/apps/gemfire/config'
default['gemfire']['config_cache']['is_cluster'] = 'true'
default['gemfire']['config_cache']['cluster_name'] = 'cluster1'
default['gemfire']['config_cache']['distr_system_id'] = '123'
